[package]
name = "evomata11"
version = "0.0.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
rand = "0.3.13"
itertools = "0.4.8"
num = "0.1.30"
crossbeam = "0.2.5"
mli = {git = "https://github.com/vadixidav/mli"}
